version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data
  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
  web: &web
    ports:
      - 3001:3001
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    entrypoint: "sh docker-entrypoint.sh"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/myapp_dev"
      REDIS_URL: "redis://redis:6379/0"
    command: bin/rails s -b 0.0.0.0 -p 3001
  sidekiq:
    <<: *web
    ports: []
    entrypoint: []
    environment:
      NOAUTH: 1
      DATABASE_URL: "postgresql://postgres:password@db:5432/myapp_dev"
      REDIS_URL: "redis://redis:6379/0"
    links:
      - redis
      - db
    command: bundle exec sidekiq -c 1
  tests:
    <<: *web
    command: bundle exec rspec
    ports: []
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/myapp_test"
      REDIS_URL: "redis://redis:6379/0"
    profiles: ['tests']
volumes:
  postgres13:
